apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-server-conf
  namespace: monitoring
data:
  prometheus.yml: |-
    global:
      scrape_interval: 15s

    scrape_configs:
    - job_name: 'prometheus'
      static_configs:
      - targets: ['localhost:9090']

    - job_name: 'windows'
      static_configs:
      - targets: ['192.168.0.183:9182']

    - job_name: 'node-exporter'
      static_configs:
      - targets: ['192.168.0.0:9100']
